### ISSUE TITLE
HTML File on ztncui controller

### ISSUE THREAD

**Issue by vicmahon** [key-networks/ztncui#38]
Hi, thanks for your amazing work at ztncui, this ui is great and easy, i got a problem with json package, it says error when installing argon. But installing controller from your site is working fine.

When im finish installing ztncui from your website, where is the src folder at? i couldnt find the www file and src/views file, so how can i add some button or function?

Thanks

**Comment by key-networks** [comment]
The packaged version (rpm or deb) does not include the src folder since it is packaged with pkg.

Did you follow the instructions at https://github.com/key-networks/ztncui to install the dependencies for argon?  You can find these under `Prerequisites`:

-  g++
- node-gyp, which can be installed with:

**Comment by vicmahon** [comment]
Thanks for the response, so where is the source file if i install the packaged version ?,  because i can't find it anywhere on var or www. i can install the dependencies but when i try to npm start, it says error because of argon version, maybe there is a newer version.

**Comment by key-networks** [comment]
You won't see source files when you install the packaged version.  You need to clone the github repository https://github.com/key-networks/ztncui
